### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JulienBrgs** [torresgol10/vsc-extension-bootstrap-class-autocomplete#1]
Hello, i've installed this extension for testing it but seem's to be not working
i'm using bootstrap 5.2 preset
i'm working on react jsx files

Thx for help :)

**Comment by JulienBrgs** [comment]
Fixed in this PR #2

**Comment by torresgol10** [comment]
Thank you very much for your pull request

**Comment by JulienBrgs** [comment]
No problem, can you publish it on VSCode marketplace ?
I need to use it 🤓

**Comment by torresgol10** [comment]
Hi @JulienBrgs, The new version with React support is out, thank you very much for using the extension and if you have any problems please let me know.

**Comment by JulienBrgs** [comment]
I had to uninstall the extension then restart VSCode to get the new version.
I was stuck on 0.0.9

thank you 💪
