### ISSUE TITLE
Autocomplete resets after pressing "-"

### ISSUE THREAD

**Issue by sinjs** [torresgol10/vsc-extension-bootstrap-class-autocomplete#3]
When you autocomplete something, and type the `-` character, the autocomplete resets itself and starts again at the beginning

**Comment by torresgol10** [comment]
Hi, thank you for using the extension, I will check the problem and have the solution as soon as possible.

**Comment by JulienBrgs** [comment]
Hello, it's fixed in this PR #4

**Comment by torresgol10** [comment]
I was already testing this option, and I will add test to avoid this, I have accepted your pull request. Thank you very much.

I do again a deploy to fix this bug in production

**Comment by torresgol10** [comment]
The new version is now in production, version 0.1.3
